### ISSUE TITLE
Reload webpages required on original install

### ISSUE THREAD

**Issue by mowens3** [kamranahmedse/tab-switcher#2]
First install requires reload of webpages to function properly. Thought it was broken initially.

**Comment by abensur** [comment]
I might be wrong but that's the expected behaviour for all extensions that are initialized in the background.js file.

**Comment by kamranahmedse** [comment]
This is expected https://github.com/kamranahmedse/tab-switcher#note
All the pre-opened tabs need to be refreshed for the first time after install.
