### ISSUE TITLE
Allow us to change the shortcut key

### ISSUE THREAD

**Issue by pateldhruv1993** [kamranahmedse/tab-switcher#3]
I just installed the extension because its seems like a good productivity tool. But damn is it hard to activate. CTRL+SHIFT+K?! That's so hard to press for me to use it regularly. I know I can just edit your js file and set up whatever I like but then I won't be able to get future updates from chrome store and all that good stuff.

Thanks!

**Comment by abensur** [comment]
This is already on the roadmap!

**Comment by wachunei** [comment]
I think this addresses a bigger issue, which is the shortcut system is injected with the rest of the extension functionality, thus being broken in some websites which already have their own shortcuts.

However, [extension can define a commands](https://developer.chrome.com/extensions/commands) and suggest a shortcut, which is configured across chrome, would be customizable and work in every website.

<img width="786" alt="screen shot 2016-09-25 at 5 14 08 pm" src="https://cloud.githubusercontent.com/assets/1024246/18817969/bb27d3d6-8343-11e6-9c6d-a67050742fec.png">

I think this is the way to approach the roadmap.

**Comment by kamranahmedse** [comment]
@wachunei I did came across this but if I had used that user would have to manually set the shortcut, which I didn't want, so I put that in a constant for now. 

However, I am working on the next release which will have an options page using which some custom shortcut will be stored in the local storage and then in the extension instead of binding that shortcut through that constant, I will use the value stored in local storage.

**Comment by wachunei** [comment]
@kamranahmedse As far as I know, the suggested shortcut (which can be different for each OS) becomes active right after installation is done, and it would not required user set up, unless user may need to change it.

**Comment by capaj** [comment]
@kamranahmedse shortcut not being active from the installation by default is a chrome feature. Maybe chrome has some good reason why they don't enable them by default. Having to set one keyboard shortcut is a small price to pay for such a great feature that the tab-switcher brings.

**Comment by akarthik10** [comment]
If you use something like BetterTouchTool, you can specify a different shortcut and map it to Ctrl+Shift+K specifically in Chrome. By the way, chrome already has a shortcut manager that allows us to specify a shortcut to "activate the extension". If you can add the functionality to show tab switcher when extension icon is clicked, one can define a custom shortcut from the keyboard shortcuts section of the extensions page in chrome.

**Comment by fharper** [comment]
That would be great as it's unusable when the tab open is GitHub

**Comment by nilbuild** [comment]
Chrome has built-in tab search now <kbd>ctr</kbd> + <kbd>shift</kbd> + <kbd>a</kbd>

![image](https://user-images.githubusercontent.com/4921183/144721083-f90b4fd4-25c0-473d-a6d8-88faea5de94b.png)
