### ISSUE TITLE
Make the shortcut global

### ISSUE THREAD

**Issue by wmertens** [kamranahmedse/tab-switcher#8]
Allow typing the shortcut from anywhere so you can be in a different application, type the shortcut, type "inbox" and you're in your inbox.

**Comment by kamranahmedse** [comment]
It is a Google Chrome extension and works only inside it so I am afraid what you are saying is not possible with it.

**Comment by wmertens** [comment]
Global shortcuts work but to show UI you need a window, you could make one
if the current window is not writeable?

**Comment by kamranahmedse** [comment]
Not sure, maybe you could create a PR :)
